'use strict';
const vscode=require('vscode');
const fs=require('node:fs');const path=require('node:path');const {spawn}=require('node:child_process');
const {LspTransport}=require('./transport.cjs');
let client;let output;let diagnostics;let context;let providers=[];
const selector={language:'nested',scheme:'file'};
const param=(d,extra={})=>({textDocument:{uri:d.uri.toString()},...extra});
const pos=p=>({line:p.line,character:p.character});
const range=r=>new vscode.Range(r.start.line,r.start.character,r.end.line,r.end.character);
const edits=e=>(e??[]).map(e=>new vscode.TextEdit(range(e.range),e.newText));
function binary(){const configured=vscode.workspace.getConfiguration('nested').get('serverPath');if(configured)return configured;const bundled=path.join(context.extensionPath,'bin',`nested${process.platform==='win32'?'.exe':''}`);return fs.existsSync(bundled)?bundled:'nested';}
function open(document){if(document.languageId==='nested')client.notify('textDocument/didOpen',{textDocument:{uri:document.uri.toString(),languageId:'nested',version:document.version,text:document.getText()}});}
async function start(){
  if(client)await client.close();for(const p of providers)p.dispose();providers=[];
  client=new LspTransport(binary(),['lsp'],{cwd:vscode.workspace.workspaceFolders?.[0]?.uri.fsPath??context.extensionPath});client.onLog=text=>output.append(text);
  client.onNotification=(method,params)=>{if(method==='textDocument/publishDiagnostics'){const uri=vscode.Uri.parse(params.uri);const document=vscode.workspace.textDocuments.find(d=>d.uri.toString()===params.uri);if(params.version!==undefined&&document&&params.version!==document.version)return;diagnostics.set(uri,params.diagnostics.map(d=>{const item=new vscode.Diagnostic(range(d.range),d.message,d.severity===2?vscode.DiagnosticSeverity.Warning:vscode.DiagnosticSeverity.Error);item.source='NESted';return item;}));}};
  await client.request('initialize',{processId:process.pid,rootUri:vscode.workspace.workspaceFolders?.[0]?.uri.toString()??null,capabilities:{general:{positionEncodings:['utf-16']}}});client.notify('initialized',{});
  for(const d of vscode.workspace.textDocuments)open(d);
  const safe=fn=>async(...args)=>{try{return await fn(...args);}catch(e){output.appendLine(String(e));return undefined;}};
  providers.push(vscode.languages.registerCompletionItemProvider(selector,{provideCompletionItems:safe(async(d,p)=>{const response=await client.request('textDocument/completion',param(d,{position:pos(p)}));return response.items.map(item=>{const c=new vscode.CompletionItem(item.label,item.kind===3?vscode.CompletionItemKind.Function:item.kind===14?vscode.CompletionItemKind.Keyword:vscode.CompletionItemKind.Variable);c.detail=item.detail;c.documentation=item.documentation;return c;});})},'(','@'));
  providers.push(vscode.languages.registerHoverProvider(selector,{provideHover:safe(async(d,p)=>{const h=await client.request('textDocument/hover',param(d,{position:pos(p)}));return h?new vscode.Hover(new vscode.MarkdownString(h.contents.value),h.range?range(h.range):undefined):null;})}));
  providers.push(vscode.languages.registerDefinitionProvider(selector,{provideDefinition:safe(async(d,p)=>{const result=await client.request('textDocument/definition',param(d,{position:pos(p)}));return result?new vscode.Location(vscode.Uri.parse(result.uri),range(result.range)):null;})}));
  providers.push(vscode.languages.registerReferenceProvider(selector,{provideReferences:safe(async(d,p,c)=>{const result=await client.request('textDocument/references',param(d,{position:pos(p),context:c}));return result.map(r=>new vscode.Location(vscode.Uri.parse(r.uri),range(r.range)));})}));
  providers.push(vscode.languages.registerRenameProvider(selector,{
    prepareRename:safe(async(d,p)=>{const result=await client.request('textDocument/prepareRename',param(d,{position:pos(p)}));if(!result)throw new Error('No renameable symbol');return {range:range(result.range),placeholder:result.placeholder};}),
    provideRenameEdits:safe(async(d,p,name)=>{const result=await client.request('textDocument/rename',param(d,{position:pos(p),newName:name}));const edit=new vscode.WorkspaceEdit();for(const[uri,changes]of Object.entries(result?.changes??{}))edit.set(vscode.Uri.parse(uri),edits(changes));return edit;})
  }));
  providers.push(vscode.languages.registerDocumentFormattingEditProvider(selector,{provideDocumentFormattingEdits:safe(async(d,options)=>edits(await client.request('textDocument/formatting',param(d,{options}))))}));
  providers.push(vscode.languages.registerDocumentSymbolProvider(selector,{provideDocumentSymbols:safe(async d=>{const result=await client.request('textDocument/documentSymbol',param(d));function symbol(s){const item=new vscode.DocumentSymbol(s.name,s.detail??'',s.kind-1,range(s.range),range(s.selectionRange));item.children=(s.children??[]).map(symbol);return item;}return result.map(symbol);})}));
  providers.push(vscode.languages.registerSignatureHelpProvider(selector,{provideSignatureHelp:safe(async(d,p)=>{const result=await client.request('textDocument/signatureHelp',param(d,{position:pos(p)}));if(!result)return null;const help=new vscode.SignatureHelp();help.activeSignature=result.activeSignature;help.activeParameter=result.activeParameter;help.signatures=result.signatures.map(s=>{const item=new vscode.SignatureInformation(s.label,s.documentation);item.parameters=s.parameters.map(p=>new vscode.ParameterInformation(p.label,p.documentation));return item;});return help;})},'(',','));
  const legend=new vscode.SemanticTokensLegend(['namespace','type','function','variable','parameter','keyword','number','string','operator'],['declaration','readonly']);
  providers.push(vscode.languages.registerDocumentSemanticTokensProvider(selector,{provideDocumentSemanticTokens:safe(async d=>{const result=await client.request('textDocument/semanticTokens/full',param(d));return new vscode.SemanticTokens(new Uint32Array(result.data));})},legend));
  providers.push(vscode.languages.registerInlayHintsProvider(selector,{provideInlayHints:safe(async(d,r)=>{const result=await client.request('textDocument/inlayHint',param(d,{range:{start:pos(r.start),end:pos(r.end)}}));return result.map(h=>new vscode.InlayHint(new vscode.Position(h.position.line,h.position.character),h.label,vscode.InlayHintKind.Type));})}));
}
async function build(check=false){const doc=vscode.window.activeTextEditor?.document;if(!doc||doc.languageId!=='nested')return;if(doc.isDirty)await doc.save();const args=check?['check',doc.uri.fsPath]:['build',doc.uri.fsPath,'--emit',path.join(path.dirname(doc.uri.fsPath),'.nested',path.basename(doc.uri.fsPath,'.nst'))];output.show(true);output.appendLine(`$ nested ${args.join(' ')}`);const child=spawn(binary(),args,{cwd:path.dirname(doc.uri.fsPath)});child.stdout.on('data',data=>output.append(data.toString()));child.stderr.on('data',data=>output.append(data.toString()));child.on('error',e=>vscode.window.showErrorMessage(`NESted: ${e.message}. Configure nested.serverPath.`));child.on('exit',code=>{if(code===0)vscode.window.showInformationMessage(check?'NESted cartridge checks passed.':`Built ${path.basename(doc.uri.fsPath,'.nst')}.nes`);else vscode.window.showErrorMessage('NESted build failed. See the NESted output channel.');});}
async function activate(ctx){context=ctx;output=vscode.window.createOutputChannel('NESted');diagnostics=vscode.languages.createDiagnosticCollection('nested');ctx.subscriptions.push(output,diagnostics);
  ctx.subscriptions.push(vscode.workspace.onDidOpenTextDocument(d=>{if(client)open(d);}),vscode.workspace.onDidChangeTextDocument(e=>{if(e.document.languageId==='nested'&&client)client.notify('textDocument/didChange',{textDocument:{uri:e.document.uri.toString(),version:e.document.version},contentChanges:[{text:e.document.getText()}]});}),vscode.workspace.onDidCloseTextDocument(d=>{if(d.languageId==='nested'&&client)client.notify('textDocument/didClose',param(d));}));
  ctx.subscriptions.push(vscode.commands.registerCommand('nested.buildROM',()=>build()),vscode.commands.registerCommand('nested.check',()=>build(true)),vscode.commands.registerCommand('nested.openPlayground',()=>vscode.env.openExternal(vscode.Uri.parse(vscode.workspace.getConfiguration('nested').get('playgroundUrl')))),vscode.commands.registerCommand('nested.restartServer',()=>start().catch(e=>vscode.window.showErrorMessage(String(e)))));
  try{await start();}catch(e){output.appendLine(String(e));vscode.window.showErrorMessage('NESted language server could not start. Build the native CLI or configure nested.serverPath.');}
}
async function deactivate(){for(const p of providers)p.dispose();if(client)await client.close();}
module.exports={activate,deactivate};
