//! LSP 3.17 services shared unchanged between the native server and WASM worker.
use std::collections::BTreeMap;
use crate::{frontend::*,json::Json};
fn obj<const N:usize>(v:[(&str,Json);N])->Json{Json::object(v)}
pub fn position(source:&str,offset:usize)->Json{let mut line=0usize;let mut character=0usize;for (p,c) in source.char_indices(){if p>=offset{break;}if c=='\n'{line+=1;character=0;}else{character+=c.len_utf16();}}obj([("line",line.into()),("character",character.into())])}
pub fn offset(source:&str,pos:&Json)->usize{let wanted_line=pos.get("line").usize();let wanted_character=pos.get("character").usize();let mut line=0usize;let mut character=0usize;for (p,c) in source.char_indices(){if line==wanted_line&&character>=wanted_character{return p;}if c=='\n'{if line==wanted_line{return p;}line+=1;character=0;}else{character+=c.len_utf16();}}source.len()}
pub fn range(source:&str,span:Span)->Json{obj([("start",position(source,span.start)),("end",position(source,span.end))])}
pub fn diagnostics(source:&str,values:&[Diagnostic])->Json{Json::Array(values.iter().map(|d|obj([("range",range(source,d.span)),("severity",Json::Number(if d.warning{2.0}else{1.0})),("source","NESted".into()),("message",d.message.clone().into())])).collect())}
struct Document{source:String,version:Json,analysis:Analysis}
#[derive(Default)]pub struct LanguageServer{documents:BTreeMap<String,Document>,pub exit:bool,shutdown:bool}
impl LanguageServer{
 pub fn new()->Self{Self::default()}
 fn notification(method:&str,params:Json)->Json{obj([("jsonrpc","2.0".into()),("method",method.into()),("params",params)])}
 fn response(id:Json,result:Json)->Json{obj([("jsonrpc","2.0".into()),("id",id),("result",result)])}
 fn failure(id:Json,code:i32,message:&str)->Json{obj([("jsonrpc","2.0".into()),("id",id),("error",obj([("code",Json::Number(code as f64)),("message",message.into())]))])}
 pub fn handle(&mut self,request:Json)->Vec<Json>{
    let method=request.get("method").str();let id=request.get("id").clone();let params=request.get("params");
    match method{
      "initialize"=>return vec![Self::response(id,obj([("capabilities",obj([
        ("positionEncoding","utf-16".into()),("textDocumentSync",obj([("openClose",true.into()),("change",Json::Number(2.0)),("save",true.into())])),
        ("hoverProvider",true.into()),("definitionProvider",true.into()),("referencesProvider",true.into()),("renameProvider",obj([("prepareProvider",true.into())])),
        ("documentSymbolProvider",true.into()),("workspaceSymbolProvider",true.into()),("documentFormattingProvider",true.into()),("inlayHintProvider",true.into()),
        ("completionProvider",obj([("triggerCharacters",Json::Array(vec!["(".into(),"@".into()]))])),
        ("signatureHelpProvider",obj([("triggerCharacters",Json::Array(vec!["(".into(),",".into()]))])),
        ("semanticTokensProvider",obj([("legend",obj([("tokenTypes",Json::Array(["namespace","type","function","variable","parameter","keyword","number","string","operator"].into_iter().map(Json::from).collect())),("tokenModifiers",Json::Array(vec!["declaration".into(),"readonly".into()]))])),("full",true.into())])),
        ("diagnosticProvider",obj([("interFileDependencies",false.into()),("workspaceDiagnostics",false.into())])),
      ])),("serverInfo",obj([("name","NESted Language Server".into()),("version",env!("CARGO_PKG_VERSION").into())]))]))],
      "initialized"|"$/cancelRequest"|"workspace/didChangeConfiguration"|"textDocument/didSave"=>return Vec::new(),
      "shutdown"=>{self.shutdown=true;return vec![Self::response(id,Json::Null)];},
      "exit"=>{self.exit=true;return Vec::new();},
      "textDocument/didOpen"=>{let d=params.get("textDocument");let uri=d.get("uri").str().to_owned();let source=d.get("text").str().to_owned();let analysis=analyze(&source);let diagnostic=diagnostics(&source,&analysis.diagnostics);self.documents.insert(uri.clone(),Document{source,version:d.get("version").clone(),analysis});return vec![Self::notification("textDocument/publishDiagnostics",obj([("uri",uri.into()),("version",d.get("version").clone()),("diagnostics",diagnostic)]))];},
      "textDocument/didChange"=>{let d=params.get("textDocument");let uri=d.get("uri").str();if let Some(doc)=self.documents.get_mut(uri){if d.get("version").usize()<=doc.version.usize(){return Vec::new();}for change in params.get("contentChanges").array(){if change.get("range").is_null(){doc.source=change.get("text").str().to_owned();}else{let r=change.get("range");let start=offset(&doc.source,r.get("start"));let end=offset(&doc.source,r.get("end"));if start<=end{doc.source.replace_range(start..end,change.get("text").str());}}}doc.version=d.get("version").clone();doc.analysis=analyze(&doc.source);return vec![Self::notification("textDocument/publishDiagnostics",obj([("uri",uri.into()),("version",doc.version.clone()),("diagnostics",diagnostics(&doc.source,&doc.analysis.diagnostics))]))];}return Vec::new();},
      "textDocument/didClose"=>{let uri=params.get("textDocument").get("uri").str();self.documents.remove(uri);return vec![Self::notification("textDocument/publishDiagnostics",obj([("uri",uri.into()),("diagnostics",Json::Array(Vec::new()))]))];},
      _=>{}
    }
    if id.is_null(){return Vec::new();}if self.shutdown{return vec![Self::failure(id,-32600,"Server has shut down")];}
    if method=="workspace/symbol"{let query=params.get("query").str().to_ascii_lowercase();let mut found=Vec::new();for (uri,d)in &self.documents{for s in &d.analysis.symbols{if s.scope.is_none()&&s.name.to_ascii_lowercase().contains(&query){found.push(obj([("name",s.name.clone().into()),("kind",s.kind.into()),("location",obj([("uri",uri.clone().into()),("range",range(&d.source,s.span))]))]));}}}return vec![Self::response(id,Json::Array(found))];}
    let uri=params.get("textDocument").get("uri").str();let Some(doc)=self.documents.get(uri)else{return vec![Self::failure(id,-32602,"Document is not open")];};let pos=offset(&doc.source,params.get("position"));
    let token=doc.analysis.tokens.iter().find(|t|t.span.start<=pos&&pos<=t.span.end&&!t.string);let symbol=token.and_then(|t|binding(&doc.analysis,&t.text,t.span.start));
    let result=match method{
      "textDocument/hover"=>{if let Some(s)=symbol{let details=if s.kind==12{if let Some(f)=doc.analysis.program.as_ref().and_then(|p|p.functions.iter().find(|f|f.name==s.name)){format!("fn {}({}) -> {}",f.name,f.params.iter().map(|p|format!("{}: {}",p.0,p.1)).collect::<Vec<_>>().join(", "),f.result)}else{format!("{}: {}",s.name,s.ty)}}else{format!("{} {}: {}\n{} byte{}",if s.mutable{"var"}else{"const"},s.name,s.ty,s.ty.size(),if s.ty.size()==1{""}else{"s"})};obj([("contents",obj([("kind","markdown".into()),("value",format!("```nested\n{details}\n```\n\nFixed-width, statically allocated NES value.").into())])),("range",range(&doc.source,token.unwrap().span))])}else if let Some(b)=token.and_then(|t|builtins().into_iter().find(|b|b.name==t.text)){obj([("contents",obj([("kind","markdown".into()),("value",format!("```nested\nfn {}({}) -> {}\n```\n\n{}",b.name,b.params.iter().map(Ty::to_string).collect::<Vec<_>>().join(", "),b.result,b.doc).into())])),("range",range(&doc.source,token.unwrap().span))])}else{Json::Null}},
      "textDocument/definition"=>symbol.map(|s|obj([("uri",uri.into()),("range",range(&doc.source,s.span))])).unwrap_or(Json::Null),
      "textDocument/completion"=>{
        let mut items=Vec::new();for s in &doc.analysis.symbols{if s.scope.is_none_or(|span|span.start<=pos&&pos<=span.end){items.push(obj([("label",s.name.clone().into()),("kind",Json::Number(if s.kind==12{3.0}else{6.0})),("detail",s.ty.to_string().into())]));}}
        for b in builtins(){items.push(obj([("label",b.name.into()),("kind",Json::Number(3.0)),("detail",format!("({}) -> {}",b.params.iter().map(Ty::to_string).collect::<Vec<_>>().join(", "),b.result).into()),("documentation",b.doc.into())]));}
        for k in ["fn","var","let","const","if","else","while","for","in","loop","return","break","continue","asm","raw","cartridge","u8","i8","u16","i16","bool","true","false"]{items.push(obj([("label",k.into()),("kind",Json::Number(14.0)),("detail","NESted language".into())]));}
        obj([("isIncomplete",false.into()),("items",Json::Array(items))])
      },
      "textDocument/signatureHelp"=>{let before=&doc.source[..pos];if let Some(open)=before.rfind('('){let name=before[..open].trim_end().rsplit(|c:char|!c.is_ascii_alphanumeric()&&c!='_').next().unwrap_or("");let b=builtins().into_iter().find(|b|b.name==name);let f=doc.analysis.program.as_ref().and_then(|p|p.functions.iter().find(|f|f.name==name));let signature=if let Some(b)=b{Some((b.name.to_owned(),b.params.iter().enumerate().map(|(i,t)|format!("arg{i}: {t}")).collect::<Vec<_>>(),b.result,b.doc.to_owned()))}else{f.map(|f|(f.name.clone(),f.params.iter().map(|p|format!("{}: {}",p.0,p.1)).collect(),f.result.clone(),String::new()))};if let Some((name,parameters,result,doc))=signature{let active=before[open+1..].matches(',').count().min(parameters.len().saturating_sub(1));obj([("signatures",Json::Array(vec![obj([("label",format!("{name}({}) -> {result}",parameters.join(", ")).into()),("documentation",doc.into()),("parameters",Json::Array(parameters.iter().map(|p|obj([("label",p.clone().into())])).collect()))])])),("activeSignature",0usize.into()),("activeParameter",active.into())])}else{Json::Null}}else{Json::Null}},
      "textDocument/prepareRename"=>symbol.map(|_|obj([("range",range(&doc.source,token.unwrap().span)),("placeholder",token.unwrap().text.clone().into())])).unwrap_or(Json::Null),
      "textDocument/rename"=>{
        let name=params.get("newName").str();if name.is_empty()||name.starts_with("__")||!name.as_bytes()[0].is_ascii_alphabetic()&&!name.starts_with('_')||!name.bytes().all(|c|c.is_ascii_alphanumeric()||c==b'_')||reserved(name){return vec![Self::failure(id,-32602,"Rename requires a nonreserved ASCII identifier")];}
        if let Some(symbol)=symbol{if doc.analysis.symbols.iter().any(|s|s.name==name&&(s.scope.is_none()||s.scope==symbol.scope)){return vec![Self::failure(id,-32602,"New name collides with an existing binding")];}let edits=references(doc,symbol,true).into_iter().map(|span|obj([("range",range(&doc.source,span)),("newText",name.into())])).collect();obj([("changes",Json::Object(BTreeMap::from([(uri.into(),Json::Array(edits))])))])}else{Json::Null}
      },
      "textDocument/references"=>symbol.map(|s|Json::Array(references(doc,s,params.get("context").get("includeDeclaration").bool()).into_iter().map(|span|obj([("uri",uri.into()),("range",range(&doc.source,span))])).collect())).unwrap_or(Json::Array(Vec::new())),
      "textDocument/documentSymbol"=>Json::Array(doc.analysis.symbols.iter().filter(|s|s.scope.is_none()).map(|s|{let full=if s.kind==12{doc.analysis.program.as_ref().and_then(|p|p.functions.iter().find(|f|f.name==s.name)).map(|f|f.span).unwrap_or(s.span)}else{s.span};let children=doc.analysis.symbols.iter().filter(|c|c.scope==Some(full)).map(|c|obj([("name",c.name.clone().into()),("detail",c.ty.to_string().into()),("kind",c.kind.into()),("range",range(&doc.source,c.span)),("selectionRange",range(&doc.source,c.span))])).collect();obj([("name",s.name.clone().into()),("detail",s.ty.to_string().into()),("kind",s.kind.into()),("range",range(&doc.source,full)),("selectionRange",range(&doc.source,s.span)),("children",Json::Array(children))])}).collect()),
      "textDocument/inlayHint"=>Json::Array(doc.analysis.symbols.iter().filter(|s|s.scope.is_some()&&!doc.source[s.span.end..].trim_start().starts_with(':')).map(|s|obj([("position",position(&doc.source,s.span.end)),("label",format!(": {}",s.ty).into()),("kind",Json::Number(1.0))])).collect()),
      "textDocument/semanticTokens/full"=>{
        let mut data=Vec::new();let mut prev_line=0;let mut prev_char=0;for t in &doc.analysis.tokens{if t.text=="<eof>"{continue;}let p=position(&doc.source,t.span.start);let line=p.get("line").usize();let character=p.get("character").usize();let len=doc.source[t.span.start..t.span.end].split('\n').next().unwrap_or("").encode_utf16().count();let kind=if t.string{7}else if parse_number(&t.text).is_some(){6}else if ["u8","i8","u16","i16","bool","void"].contains(&t.text.as_str()){1}else if reserved(&t.text)&&!builtins().iter().any(|b|b.name==t.text){5}else if binding(&doc.analysis,&t.text,t.span.start).is_some_and(|s|s.kind==12)||builtins().iter().any(|b|b.name==t.text){2}else if t.text.as_bytes().first().is_some_and(|b|b.is_ascii_alphabetic()||*b==b'_'){3}else{8};let mods=binding(&doc.analysis,&t.text,t.span.start).map(|s|usize::from(s.span==t.span)|(usize::from(!s.mutable)<<1)).unwrap_or(0);data.extend([line-prev_line,if line==prev_line{character-prev_char}else{character},len,kind,mods].map(Json::from));prev_line=line;prev_char=character;}obj([("data",Json::Array(data))])
      },
      "textDocument/diagnostic"=>obj([("kind","full".into()),("items",diagnostics(&doc.source,&doc.analysis.diagnostics))]),
      "textDocument/formatting"=>{let mut indent=0usize;let mut out=String::new();for line in doc.source.lines(){let trim=line.trim();if trim.is_empty(){out.push('\n');continue;}let leading=trim.chars().take_while(|c|*c=='}').count();let this=indent.saturating_sub(leading);out.push_str(&"  ".repeat(this));out.push_str(trim);out.push('\n');let tokens=lex(trim).unwrap_or_default();let opens=tokens.iter().filter(|t|!t.string&&t.text=="{").count();let closes=tokens.iter().filter(|t|!t.string&&t.text=="}").count();indent=(indent+opens).saturating_sub(closes);}Json::Array(vec![obj([("range",range(&doc.source,Span{start:0,end:doc.source.len()})),("newText",out.into())])])},
      _=>return vec![Self::failure(id,-32601,"Method not found")],
    };vec![Self::response(id,result)]
 }
}
fn binding<'a>(analysis:&'a Analysis,name:&str,pos:usize)->Option<&'a Symbol>{analysis.symbols.iter().find(|s|s.name==name&&s.scope.is_some_and(|span|span.start<=pos&&pos<=span.end)).or_else(||analysis.symbols.iter().find(|s|s.name==name&&s.scope.is_none()))}
fn references(doc:&Document,s:&Symbol,include:bool)->Vec<Span>{doc.analysis.tokens.iter().filter(|t|!t.string&&t.text==s.name&&(include||t.span!=s.span)&&binding(&doc.analysis,&t.text,t.span.start).is_some_and(|b|b.span==s.span)).map(|t|t.span).collect()}
fn reserved(s:&str)->bool{["fn","var","let","const","if","else","while","for","in","loop","return","break","continue","asm","raw","cartridge","u8","i8","u16","i16","bool","void","true","false","asset"].contains(&s)||builtins().iter().any(|b|b.name==s)}
#[cfg(test)]mod tests{use super::*;
 #[test]fn utf16_positions(){let source="// 🎸\nvar 音 = 1;";let p=position(source,source.find('音').unwrap());assert_eq!(p.get("line").usize(),1);assert_eq!(p.get("character").usize(),4);assert_eq!(offset(source,&p),source.find('音').unwrap());let p=position("a🎸b",5);assert_eq!(p.get("character").usize(),3);assert_eq!(offset("a🎸b",&p),5);}
 #[test]fn rename_uses_binding(){let mut l=LanguageServer::new();let source="var score: u8 = 0; fn update() { score += 1; text(0,0,\"score\"); }";let req=obj([("method","textDocument/didOpen".into()),("params",obj([("textDocument",obj([("uri","file:///a.nst".into()),("text",source.into()),("version",1usize.into())]))]))]);assert!(l.handle(req)[0].get("params").get("diagnostics").array().is_empty());let r=l.handle(obj([("id",1usize.into()),("method","textDocument/rename".into()),("params",obj([("textDocument",obj([("uri","file:///a.nst".into())])),("position",position(source,4)),("newName","points".into())]))]));assert_eq!(r[0].get("result").get("changes").get("file:///a.nst").array().len(),2);}
}
